GET http://localhost:9000/users

###
POST http://localhost:9000/users/create
Content-Type: application/json

{
    "name": "I Gusti",
    "email": "gusti@gmail.com",
    "password": "password"
}

###
GET http://localhost:9000/users/1

###
PATCH  http://localhost:9000/users/update/1
Content-Type: application/json

{
    "name": "Kuswara",
    "email": "kuswarask8er@gmail.com",
    "password": "password"
}

###
DELETE http://localhost:9000/users/delete/4


###
GET http://localhost:9000/assets/images/1.jpg

###

